export interface KnowledgeCard {
  id: string;
  category: 'knowledge' | 'tip' | 'world';
  badge: string;
  fact: string;
  icon: string;
}

export const cookingFacts = {
  did_you_know: [
    "🍅 Tomatoes were once called \"poison apples\" in Europe.",
    "🧄 Crushing garlic releases allicin, its powerful aroma compound.",
    "🧈 Clarified butter (ghee) withstands higher heat than regular butter.",
    "🥖 Bread rises because yeast releases carbon dioxide bubbles.",
    "🧂 A pinch of salt enhances sweetness in desserts.",
    "🧪 Browning food triggers the Maillard reaction—flavor magic at 300°F.",
    "🧊 Ice cream was once a luxury only for royalty.",
    "🥛 Milk chocolate was invented in Switzerland in the 1800s.",
    "🍯 Honey never spoils—archaeologists found edible honey in tombs.",
    "🍚 Sushi rice was originally used to preserve fish, not eaten.",
    "🥔 Potatoes were the first vegetable grown in space.",
    "🥚 The green ring on boiled eggs comes from iron reacting with sulfur.",
    "🧅 Onions make you cry by releasing sulfuric acid vapors.",
    "🍞 The holes in Swiss cheese come from gas bubbles made by bacteria.",
    "🍋 Lemons float, but limes sink—they're denser!",
    "🥕 Carrots were originally purple, not orange.",
    "🌶 Chili heat doesn't come from taste buds but pain receptors.",
    "🍄 Mushrooms are closer to humans than to plants genetically.",
    "🍎 Apples float because 25% of their volume is air.",
    "🍇 The white dust on grapes is natural yeast, not pesticides.",
    "🍫 White chocolate isn't real chocolate—it has no cocoa solids.",
    "🧃 Ketchup was once sold as medicine in the 1800s.",
    "🍻 Yeast was first used in bread thousands of years before beer.",
    "🧈 Butter turns white when whipped because of trapped air bubbles.",
    "🥩 \"Umami\" was only recognized as the fifth taste in 2002.",
    "🍵 Green tea and black tea come from the same plant—just processed differently.",
    "🍠 Sweet potatoes aren't related to regular potatoes.",
    "🧄 Garlic's flavor strengthens after chopping because of enzyme reactions.",
    "🍌 Bananas are berries, but strawberries aren't.",
    "🌾 Rice feeds more than half the world's population.",
    "🍷 Wine grapes are smaller and sweeter than table grapes.",
    "🧊 Sea salt and table salt taste the same—texture makes the difference.",
    "🥬 Lettuce was once considered a sleep aid in ancient Rome.",
    "🍅 Refrigerating tomatoes dulls their flavor.",
    "🧈 Margarine was invented as a cheaper butter substitute in wartime.",
    "🥑 Avocados are botanically large berries with one seed.",
    "🥖 Bread goes stale faster in the fridge than on the counter.",
    "🍯 Honey bees visit 2 million flowers to make one pound of honey.",
    "🧀 Cheese predates recorded history—found in ancient Egyptian tombs.",
    "🥛 Lactose intolerance is the world's default—tolerance is the mutation.",
    "🥚 Eggs age faster at room temperature than in the fridge.",
    "🍫 Dark chocolate contains antioxidants that can lower stress levels.",
    "🍇 Grapes explode in the microwave — don't try it at home!",
    "🧂 Humans are the only animals who season food deliberately.",
    "🍏 Green apples are more acidic than red ones, which is why they taste sharper.",
    "🥔 Sweet potatoes and yams are from entirely different plant families.",
    "🌽 Corn always has an even number of rows on each cob.",
    "🍞 Sourdough bread naturally resists mold because of its acidity.",
    "🧄 Black garlic is just regular garlic aged under controlled heat and humidity.",
    "🍗 Chicken skin crisps best when completely dry before cooking.",
    "🥦 Broccoli contains more vitamin C than an orange.",
    "🧈 Butter was discovered accidentally while carrying milk in animal skins.",
    "🍅 The red color in tomatoes comes from lycopene, a natural antioxidant.",
    "🍠 Baking sweet potatoes converts starch into sugar — that's why they taste sweeter.",
    "🧃 Oranges aren't always orange — in warm climates, they stay green when ripe.",
    "🥩 \"Rare\" steak is safe because bacteria live on the surface, not inside.",
    "🍞 Fresh bread goes stale faster than day-old bread because of moisture redistribution.",
    "🧄 The more you crush garlic, the stronger it tastes.",
    "🍎 Apples emit ethylene gas, which ripens other fruits nearby.",
    "🥛 Shaking cream too long makes butter — and buttermilk as a byproduct.",
    "🧀 Parmesan cheese contains naturally occurring MSG — that's umami flavor!",
    "🍅 Tomatoes are technically fruits, but the U.S. declared them vegetables for tax reasons.",
    "🧊 Ice cubes made with boiled water are clearer than with tap water.",
    "🍯 Honey crystallizes because glucose separates from water — still perfectly edible.",
    "🥦 Steaming preserves more nutrients than boiling.",
    "🧂 Kosher salt isn't about religion — it's about large crystal size for drawing out moisture.",
    "🍓 Strawberries have about 200 seeds on each berry.",
    "🥕 Baby carrots are just shaped-down full carrots.",
    "🍿 Popcorn pops when internal moisture turns to steam and bursts the kernel.",
    "🧅 Red onions turn blue-green when cooked with alkaline foods like baking soda.",
    "🧈 Whipped butter spreads easier because air makes it less dense.",
    "🥩 Marbling in beef is intramuscular fat — key to tenderness.",
    "🍌 Bananas glow faintly blue under blacklight due to chlorophyll breakdown.",
    "🍷 The \"legs\" on wine glass sides indicate alcohol content, not quality.",
    "🥛 Lactose-free milk tastes sweeter because lactose is broken into simpler sugars.",
    "🧄 Elephant garlic is actually closer to a leek than garlic.",
    "🍞 Flatbreads exist in nearly every culture — tortillas, naan, pita, lavash.",
    "🧂 Pink Himalayan salt gets its color from iron oxide (rust).",
    "🥚 Egg yolks are naturally different shades of yellow depending on the hen's diet.",
    "🧠 Your sense of taste weakens when you're cold — that's why warm food tastes richer."
  ],
  chef_tips: [
    "🔥 Always preheat your pan—it prevents sticking and boosts flavor.",
    "🧅 Salt onions early to draw out moisture and caramelize faster.",
    "🧄 Add garlic last—it burns easily and turns bitter.",
    "🍋 A splash of acid brightens any dish instantly.",
    "🧊 Chill cookie dough before baking for thicker cookies.",
    "🧂 Season in layers, not all at once, for balanced flavor.",
    "🍝 Save pasta water—it helps sauce cling beautifully.",
    "🧈 Butter makes sauces glossy—add a small cube at the end.",
    "🥄 Taste constantly—seasoning is a dialogue, not a recipe.",
    "🥔 Boil potatoes in cold water for even cooking.",
    "🧀 Let cheese reach room temperature before serving for best flavor.",
    "🥩 Rest meat before slicing to retain juices.",
    "🌿 Tear herbs instead of chopping to preserve aroma.",
    "🧊 Freeze broth in cubes for quick flavor boosts later.",
    "🍞 Toast nuts before using to deepen flavor.",
    "🍳 For fluffy scrambled eggs, cook low and slow.",
    "🧅 Use a damp paper towel to keep chopped herbs fresh.",
    "🍅 Salt tomatoes right before serving—too early draws out water.",
    "🥬 Wash greens in cold water to make them crisp again.",
    "🍗 Pat meat dry before searing—it browns, not steams.",
    "🧄 Store garlic in a cool, dry place—never the fridge.",
    "🥒 Sprinkle salt on cucumbers to remove excess water.",
    "🧂 Salt pasta water like the sea—it's your only chance to season it deeply.",
    "🍚 Let rice rest for 10 minutes after cooking—fluffier texture.",
    "🧈 Use unsalted butter when baking to control salt levels.",
    "🥕 Don't peel carrots unless you need to—most nutrients are in the skin.",
    "🍋 Roll lemons before juicing to extract more juice.",
    "🍇 Use a serrated knife for cutting soft fruits and tomatoes.",
    "🥄 Deglaze pans with wine or stock to capture all the flavor bits.",
    "🧊 Cool soups before blending to prevent splashes.",
    "🍫 Melt chocolate slowly over gentle heat—don't rush it.",
    "🧅 Cut onions near an open flame to reduce tears.",
    "🥩 Slice meat against the grain for tenderness.",
    "🥛 When whipping cream, chill bowl and whisk first.",
    "🍲 Simmer, don't boil soups, to keep flavors clear.",
    "🧄 Rub your hands on stainless steel to remove garlic smell.",
    "🥔 Use vinegar in boiling water to keep potatoes from falling apart.",
    "🌶 Toast spices before grinding for stronger aroma.",
    "🍞 Let bread dough rise twice for better texture.",
    "🧂 Salt your cutting board when chopping herbs—it keeps them from flying.",
    "🔪 Keep knives sharp — dull ones are more dangerous.",
    "🍳 Use room-temperature eggs for smoother batters.",
    "🧄 Don't overcrowd your pan — it lowers heat and steams food.",
    "🧂 Season raw meat at least 15 minutes before cooking.",
    "🍋 Add acid after heat to preserve freshness.",
    "🧈 Add butter to sauces off heat to prevent separation.",
    "🥦 Don't salt green vegetables until after blanching — it dulls their color.",
    "🍅 Use a serrated knife for slicing ripe tomatoes.",
    "🥕 Cut vegetables the same size for even cooking.",
    "🧊 Freeze stock in small portions to add depth to quick meals.",
    "🍗 Use a thermometer — guessing doneness leads to dry meat.",
    "🥬 Soak wilted lettuce in ice water to revive it.",
    "🧂 Always taste before adding more salt — some ingredients bring their own.",
    "🍞 Brush bread with water before reheating for a fresh crust.",
    "🍝 Stir pasta right after adding to boiling water to prevent clumping.",
    "🧅 Cook onions low and slow for deep, sweet caramelization.",
    "🍳 For perfect fried eggs, cover the pan to steam the top.",
    "🧄 Store herbs upright in a jar of water like flowers.",
    "🍚 For sticky rice, rinse less; for fluffy rice, rinse more.",
    "🥩 Flip steaks only once for a good crust.",
    "🥕 Roast vegetables on a single layer — overcrowding traps steam.",
    "🍫 Add espresso powder to chocolate desserts for a richer flavor.",
    "🧂 Salt tomatoes right before serving to keep them juicy.",
    "🍯 Add a little honey or sugar to tomato sauce to balance acidity.",
    "🥄 Use lemon zest instead of juice for a subtle citrus aroma.",
    "🍳 Don't stir scrambled eggs constantly—let them set slightly for softness.",
    "🧄 When frying garlic, watch color—golden, not brown, is perfect.",
    "🍗 Rest roasted chicken 10 minutes before carving to keep it juicy.",
    "🥬 Massage kale with oil to soften it for salads.",
    "🍋 Use citrus zest in dressings for brightness without sourness.",
    "🧈 Melt butter slowly for clear clarified butter.",
    "🥛 For fluffier pancakes, don't overmix the batter.",
    "🧊 Chill cookie sheets before baking to reduce spreading.",
    "🧅 Keep onion halves in a sealed bag—they absorb odors in the fridge.",
    "🥔 Soak cut fries in cold water before frying for crispier results.",
    "🧂 Use flaky sea salt to finish dishes—it adds crunch and bursts of flavor.",
    "🥩 Marinate meats in acid (like yogurt or vinegar) to tenderize.",
    "🍇 Don't wash berries until ready to eat—they spoil faster wet.",
    "🥣 Always scrape the brown bits (fond) off the pan—that's pure flavor.",
    "🍞 Let pie dough rest after rolling to prevent shrinking."
  ],
  around_the_world: [
    "🇮🇹 Italians save pasta water and call it \"liquid gold.\"",
    "🇯🇵 Japanese chefs sharpen their knives daily out of respect for ingredients.",
    "🇫🇷 The word \"restaurant\" comes from the French restaurer, meaning \"to restore.\"",
    "🇮🇳 Curry is not a single dish—it represents hundreds of spice blends.",
    "🇲🇽 Mexican mole sauce can include over 20 ingredients, even chocolate.",
    "🇨🇳 Dumplings were invented as medicine to warm people in winter.",
    "🇹🇭 Thai cuisine balances four flavors: sweet, sour, salty, spicy.",
    "🇬🇷 The Mediterranean diet is recognized as one of the healthiest in the world.",
    "🇰🇷 Kimchi dates back over 2,000 years in Korea.",
    "🇫🇷 Croissants originated in Austria, not France.",
    "🇯🇵 Sushi began as a preservation method for fish.",
    "🇮🇹 Pizza Margherita was named after a queen of Italy.",
    "🇹🇷 Turkish coffee is so strong it's served with water to cleanse the palate.",
    "🇪🇸 Spain's tapas tradition began as bread slices placed on wine glasses.",
    "🇨🇳 Tea was discovered by accident when leaves fell into boiling water.",
    "🇲🇽 Tacos were originally eaten by silver miners as quick meals.",
    "🇮🇳 Chai means \"tea\" — so \"chai tea\" literally means \"tea tea.\"",
    "🇯🇲 Jerk seasoning originated with escaped enslaved Africans in Jamaica.",
    "🇨🇭 Swiss fondue was created to use up old cheese and bread.",
    "🇻🇳 Vietnamese pho is traditionally a breakfast food.",
    "🇬🇧 Fish and chips became popular during Britain's industrial revolution.",
    "🇫🇷 Escargot (snails) was once poor man's food.",
    "🇲🇦 Moroccan tagines are named after the clay pot they're cooked in.",
    "🇨🇦 Poutine was invented in rural Quebec in the 1950s.",
    "🇨🇳 Fortune cookies actually originated in California.",
    "🇮🇹 Espresso means \"pressed out,\" referring to how it's brewed.",
    "🇯🇵 Ramen arrived from China and evolved into a Japanese classic.",
    "🇬🇷 Greek olive trees can live for hundreds of years.",
    "🇲🇽 The word \"chocolate\" comes from the Aztec xocolatl.",
    "🇫🇷 Ratatouille was originally a peasant stew of leftovers.",
    "🇹🇭 \"Pad Thai\" was promoted as a national dish to unite the country.",
    "🇨🇳 Chopsticks predate forks by over 2,000 years.",
    "🇺🇸 The hamburger likely originated in Germany, not America.",
    "🇮🇳 Indian spices were once more valuable than gold.",
    "🇧🇷 Feijoada, Brazil's national dish, was created by enslaved Africans.",
    "🇮🇹 Gelato has less air than ice cream—denser and more flavorful.",
    "🇯🇵 Bento boxes began as portable meals for travelers.",
    "🇲🇽 Corn was first domesticated over 9,000 years ago in Mexico.",
    "🇹🇷 Baklava's origins are shared across the Middle East and Balkans.",
    "🇫🇷 In France, bread is considered sacred—throwing it away is bad luck."
  ]
};

export function getRandomKnowledgeCard(): KnowledgeCard {
  const categories = Object.keys(cookingFacts) as Array<keyof typeof cookingFacts>;
  const randomCategory = categories[Math.floor(Math.random() * categories.length)];
  const facts = cookingFacts[randomCategory];
  const randomFact = facts[Math.floor(Math.random() * facts.length)];
  
  const categoryMap = {
    did_you_know: { badge: 'Did You Know?', icon: '🧠' },
    chef_tips: { badge: 'Chef Tip', icon: '🍳' },
    around_the_world: { badge: 'Around the World', icon: '🌍' }
  };
  
  const { badge, icon } = categoryMap[randomCategory as keyof typeof categoryMap];
  
  return {
    id: `${randomCategory}-${Math.random().toString(36).substr(2, 9)}`,
    category: randomCategory as 'knowledge' | 'tip' | 'world',
    badge,
    fact: randomFact,
    icon
  };
}
